(part "B340LA-13-F"
    (packageRef "DIOM5226X240N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "621-B340LA-F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/B340LA-13-F?qs=dU8xVB810ithG3OzkYQiSg%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "B340LA-13-F")
    (property "Description" "Diodes Inc B340LA-13-F, SMT Schottky Diode, 40V 3A, 2-Pin DO-214AC")
    (property "Datasheet_Link" "")
    (property "symbolName1" "B340LA-13-F")
)
