(part "TPS5420QDRQ1"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "BOOT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VSENSE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ENA") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VIN") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PH") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS5420QDRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS5420QDRQ1?qs=wkx8pu8tL7J7TtwDHJoKDw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS5420QDRQ1")
    (property "Description" "Voltage Regulators - Switching Regulators 2A Wide-Input-Range Step-Down Converter")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tps5420-q1.pdf")
    (property "symbolName1" "TPS5420QDRQ1")
)
