(part "INA199C3DCKR"
    (packageRef "SOT65P210X110-6N")
    (interface
        (port "1" (symbPinId 1) (portName "REF") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "V+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IN+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN-") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "595-INA199C3DCKR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/INA199C3DCKR?qs=0C8XhJW8e4r6fLKZGUND2A%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "INA199C3DCKR")
    (property "Description" "26V, bi-directional, zero-drift, low-/high-side, voltage output current sense amplifier")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/INA199")
    (property "symbolName1" "INA199C3DCKR")
)
